server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service
  datasource:
    url: "jdbc:postgresql://localhost:5433/lms_db?currentSchema=auth_schema&options=-c timezone=UTC"
    username: ${SPRING_DATASOURCE_PASSWORD:user}
    password: ${SPRING_DATASOURCE_USERNAME:password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
    cache:
      type: redis
      redis:
        cache-null-values: false
        time-to-live: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000

springdoc:
  api-docs:
    enabled: true
    path: /api/auth/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/auth/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,prometheus"
  metrics:
    export:
      prometheus:
        enabled: true