server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service
  datasource:
    url: "jdbc:postgresql://localhost:5433/lms_db?currentSchema=auth_schema&options=-c timezone=UTC"
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

springdoc:
  api-docs:
    enabled: true
    path: /api/auth/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/auth/swagger-ui.html