server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: "jdbc:postgresql://localhost:5433/lms_db?currentSchema=auth_schema&options=-c timezone=UTC"
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

eureka:
  client:
    enabled: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
