services:
  postgres-db:
    image: postgres:16
    container_name: lms-micro-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms_db
    ports:
      - "5433:5432"
    volumes:
      - lms_postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: lms-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    image: ghcr.io/yuriu-zhuravlev/lcm-microservices/eureka-server:latest
    container_name: lms-eureka
    ports:
      - "8761:8761"

  redis:
    image: redis:7.2-alpine
    container_name: lms-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: always

  auth-service:
    image: ghcr.io/yuriu-zhuravlev/lcm-microservices/auth-service:latest
    container_name: lms-auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/lms_db?currentSchema=auth_schema&options=-c%20timezone=UTC
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      postgres-db:
        condition: service_started
      eureka-server:
        condition: service_started
      redis:
        condition: service_healthy

  course-service:
    image: ghcr.io/yuriu-zhuravlev/lcm-microservices/course-service:latest
    container_name: lms-course-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/lms_db?currentSchema=courses_schema&options=-c%20timezone=UTC
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - rabbitmq
      - eureka-server
      - redis

  learning-service:
    image: ghcr.io/yuriu-zhuravlev/lcm-microservices/learning-service:latest
    container_name: lms-learning-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/lms_db?currentSchema=learning_schema&options=-c%20timezone=UTC
      SPRING_RABBITMQ_HOST: rabbitmq
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - postgres-db
      - rabbitmq
      - eureka-server
      - redis

  api-gateway:
    image: ghcr.io/yuriu-zhuravlev/lcm-microservices/api-gateway:latest
    container_name: lms-api-gateway
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server

volumes:
  lms_postgres_data: