apiVersion: v1
kind: ConfigMap
metadata:
  name: course-service-config
  namespace: lms
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/lms_db?currentSchema=courses_schema&options=-c%20timezone=UTC"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_RABBITMQ_HOST: "rabbitmq"