server:
  port: 8083
  forward-headers-strategy: framework

spring:
  application:
    name: learning-service

  datasource:
    url: jdbc:postgresql://localhost:5433/lms_db?currentSchema=learning_schema&options=-c timezone=UTC
    username: ${SPRING_DATASOURCE_PASSWORD:user}
    password: ${SPRING_DATASOURCE_USERNAME:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: learning_schema
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
    cache:
      type: redis
      redis:
        cache-null-values: false
        time-to-live: 3600000

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000ms
          max-attempts: 5
          multiplier: 2.0
          max-interval: 30000ms
        acknowledge-mode: auto
        default-requeue-rejected: false

  flyway:
    enabled: true
    schemas: learning_schema
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    io.github.resilience4j: DEBUG

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: 86400000

springdoc:
  api-docs:
    enabled: true
    path: /api/learning/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/learning/swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,circuitbreakers,circuitbreakerevents,prometheus"
  health:
    circuitbreakers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        slow-call-duration-threshold: 2s
        slow-call-rate-threshold: 80
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      course-service:
        base-config: default

  timelimiter:
    configs:
      default:
        timeout-duration: 3s
        cancel-running-future: true
    instances:
      course-service:
        base-config: default