loki:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"

fluent-bit:
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "50m"
      memory: "100Mi"

grafana:
  resources:
    limits:
      cpu: "300m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"

prometheus:
  enabled: true
  server:
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "100m"
        memory: "256Mi"
  alertmanager:
    enabled: false