apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: lms
data:
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka-server:8761/eureka/"
  SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED: "true"
  SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_LOWER_CASE_SERVICE_ID: "true"