apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: {{ include "lms.namespace" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: {{ .Values.global.imageRegistry }}/eureka-server:{{ .Values.global.imageTag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
              - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
            - name: EUREKA_SERVER_ENABLE_SELF_PRESERVATION
              value: "false"
          resources:
            {{- toYaml .Values.eureka.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: {{ include "lms.namespace" . }}
spec:
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
    - port: 8761
      targetPort: 8761