{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: lms-secret-store
  namespace: {{ include "lms.namespace" . }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: lms-eso-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lms-external-secret
  namespace: {{ include "lms.namespace" . }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: lms-secret-store
    kind: SecretStore
  target:
    name: lms-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: /lms/prod-secrets
        property: jwt-secret
    - secretKey: SPRING_DATASOURCE_USERNAME
      remoteRef:
        key: /lms/prod-secrets
        property: db-username
    - secretKey: SPRING_DATASOURCE_PASSWORD
      remoteRef:
        key: /lms/prod-secrets
        property: db-password
    - secretKey: SPRING_RABBITMQ_USERNAME
      remoteRef:
        key: /lms/prod-secrets
        property: rabbitmq-user
    - secretKey: SPRING_RABBITMQ_PASSWORD
      remoteRef:
        key: /lms/prod-secrets
        property: rabbitmq-password
{{- end }}