apiVersion: v1
kind: ConfigMap
metadata:
  name: learning-service-config
  namespace: {{ include "lms.namespace" . }}
  labels:
    {{- include "lms.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: {{ .Values.learningService.datasourceUrl | quote }}
  SPRING_DATA_REDIS_HOST: {{ .Values.global.redis.host | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.global.redis.port | quote }}
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: {{ .Values.eurekaUrl | quote }}
  SPRING_RABBITMQ_HOST: "rabbitmq"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learning-service
  namespace: {{ include "lms.namespace" . }}
spec:
  {{- if not .Values.learningService.hpa.enabled }}
  replicas: {{ .Values.learningService.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: learning-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: learning-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8083"
    spec:
      initContainers:
        - name: wait-for-deps
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z {{ .Values.global.postgres.host }} 5432 && nc -z {{ .Values.global.redis.host }} 6379 && nc -z eureka-server 8761 && nc -z rabbitmq 5672; do sleep 3; done']
      containers:
        - name: learning-service
          image: {{ .Values.global.imageRegistry }}/{{ .Values.learningService.image }}:{{ .Values.global.imageTag }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.learningService.port }}
          envFrom:
            - configMapRef:
                name: learning-service-config
            - secretRef:
                name: lms-secrets
          resources:
            {{- toYaml .Values.learningService.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.learningService.port }}
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.learningService.port }}
            initialDelaySeconds: 120
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: learning-service
  namespace: {{ include "lms.namespace" . }}
spec:
  type: ClusterIP
  selector:
    app: learning-service
  ports:
    - port: {{ .Values.learningService.port }}
      targetPort: {{ .Values.learningService.port }}